direction: right

# Nodes (Devices and Ports)
"OCX光-ONU": {
  "port1"
}
"SAKURA-J3-02": {
  "ge-0/0/0-仮"
  "ge-0/0/1-仮"
}
"SW-J3-02": {
  "mge-0/0/0"
}
"SAKURA-J3-01": {
  "ge-0/0/0-仮"
  "ge-0/0/1-仮"
}
"RT-J3-01": {
  "lan3:10"
  "lan2:9"
}
"SW-J3-01": {
  "mge-0/0/0"
  "xe-0/2/0"
}

# Connections
"RT-J3-01"."lan3:10" -- "SW-J3-01"."xe-0/2/0"
"OCX光-ONU"."port1" -- "RT-J3-01"."lan2:9"
"SAKURA-J3-02"."ge-0/0/0-仮" -- "SW-J3-02"."mge-0/0/0"
"SW-J3-01"."mge-0/0/0" -- "SAKURA-J3-01"."ge-0/0/0-仮"
"SAKURA-J3-02"."ge-0/0/1-仮" -- "SAKURA-J3-01"."ge-0/0/1-仮"
